### ISSUE TITLE
Switch and Tabs components failing to run.

### ISSUE THREAD

**Issue by r3donnx** [vue-bulma/vue-admin#137]
Hi, I am trying to run vue-admin on my mac, but it fails.
I am using OSX 10.12.1
npm -v
4.0.5
node -v
v7.4.0

vue-admin runs fine if I delete Switch.vue and Tabs.vue components from client/views/components.

 I am getting the following errors:
`ERROR in ../~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-bulma-switch/src/Switch.vue
Module parse failed: /Users/r3d/Dev/node_modules/buble-loader/index.js!/Users/r3d/Dev/tsceo/node_modules/vue-loader/lib/selector.js?type=script&index=0!/Users/r3d/Dev/tsceo/node_modules/vue-bulma-switch/src/Switch.vue Unexpected token (34:22)
You may need an appropriate loader to handle this file type.
|       var value = ref.value;
|       var obj;
|       return ( obj = {,
|         checked: value
|       }, obj[("is-" + type)] = type, obj[("is-" + size)] = size, obj )
 @ ./~/vue-bulma-switch/src/Switch.vue 8:18-100
 @ ../~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./client/views/components/Switch.vue
 @ ./client/views/components/Switch.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/store/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ../~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-bulma-tabs/src/Tabs.vue
Module build failed: Error
    at Node.initialise (/Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:2004:65)
    at /Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:9381:56
    at Array.forEach (native)
    at Node.initialise (/Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:9381:15)
    at Node.initialise (/Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:858:12)
    at Node.initialise (/Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:2098:31)
    at Node.initialise (/Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:858:12)
    at /Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:856:61
    at Array.forEach (native)
    at Node.initialise (/Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:856:12)
    at Node.initialise (/Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:858:12)
    at /Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:856:61
    at Array.forEach (native)
    at Node.initialise (/Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:856:12)
    at Node.initialise (/Users/r3d/Dev/node_modules/buble/dist/buble.umd.js:858:12)
 @ ./~/vue-bulma-tabs/src/Tabs.vue 8:18-98
 @ ./~/vue-bulma-tabs/src/index.js
 @ ../~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./client/views/components/Tabs.vue
 @ ./client/views/components/Tabs.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/store/modules/menu/lazyLoading.js
 @ ./client/store/modules/menu/index.js
 @ ./client/store/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app`

**Comment by luventa** [comment]
Thanks for raising this and sorry for replying late.
I think remove and re-install the node_modules may solve this. Or it could be a compatibility issue.

**Comment by thekordy** [comment]
me too using ubuntu 16.04
node -v
v6.9.5
npm -v
3.10.10

also performed these steps as advised but yet same issue
```bash
rm -rf node_modules
npm cache clean
npm i -d
npm run dev
```

**Comment by luventa** [comment]
Will try on these environment
