### ISSUE TITLE
I clone down, npm run dev error，The error message is as follows

### ISSUE THREAD

**Issue by 744934982** [vue-bulma/vue-admin#199]
ERROR in ./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-43305f1c","scoped":false,"hasInlineConfig":true}!./~/sass-loader/lib/loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./client/App.vue
Module build failed: Error: Missing binding E:\work\VueJs\vue-admin\node_modules\node-sass\vendor\win32-x64-46\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 4.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (E:\work\VueJs\vue-admin\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (E:\work\VueJs\vue-admin\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\work\VueJs\vue-admin\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at loadLoader (E:\work\VueJs\vue-admin\node_modules\loader-runner\lib\loadLoader.js:13:17)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-43305f1c","scoped":false,"hasInlineConfig":true}!./~/sass-loader/lib/loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./client/App.vue 4:14-303 13:3-17:5 14:22-311
 @ ./client/App.vue
 @ ./client/app.js
 @ ./client/index.js
 @ multi ./build/dev-client ./client/index.js

Mainly he repeated the mistake

**Comment by QuincyX** [comment]
me too

**Comment by caiping92** [comment]
me too

**Comment by luventa** [comment]
You need Nodejs v5+
Check [Prerequisites](https://github.com/vue-bulma/vue-admin/wiki/Guide#prerequisites)
