### ISSUE TITLE
node install 报错

### ISSUE THREAD

**Issue by itsmikej** [vue-bulma/vue-admin#225]
你好，我按照我这边好像也是 安装node-sass出错了

我按照这个步骤安装：
```
1. rm -rf node_modules
2. npm i -d --registry=https://registry.npm.taobao.org
3. npm run dev
```

执行第2步的时候报错，信息如下：

```shell
er.o Release/obj.target/libsass/src/libsass/src/listize.o Release/obj.target/libsass/src/libsass/src/memory_manager.o Release/obj.target/libsass/src/libsass/src/node.o Release/obj.target/libsass/src/libsass/src/output.o Release/obj.target/libsass/src/libsass/src/parser.o Release/obj.target/libsass/src/libsass/src/plugins.o Release/obj.target/libsass/src/libsass/src/position.o Release/obj.target/libsass/src/libsass/src/prelexer.o Release/obj.target/libsass/src/libsass/src/remove_placeholders.o Release/obj.target/libsass/src/libsass/src/sass.o Release/obj.target/libsass/src/libsass/src/sass2scss.o Release/obj.target/libsass/src/libsass/src/sass_context.o Release/obj.target/libsass/src/libsass/src/sass_functions.o Release/obj.target/libsass/src/libsass/src/sass_util.o Release/obj.target/libsass/src/libsass/src/sass_values.o Release/obj.target/libsass/src/libsass/src/source_map.o Release/obj.target/libsass/src/libsass/src/to_c.o Release/obj.target/libsass/src/libsass/src/to_value.o Release/obj.target/libsass/src/libsass/src/units.o Release/obj.target/libsass/src/libsass/src/utf8_string.o Release/obj.target/libsass/src/libsass/src/util.o Release/obj.target/libsass/src/libsass/src/values.o
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/sass.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/itsmikej/code/vue/vue-admin/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.4.0/bin/node" "/Users/itsmikej/code/vue/vue-admin/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/itsmikej/code/vue/vue-admin/node_modules/wysiwyg.css/node_modules/node-sass
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm info lifecycle node-sass@3.13.1~postinstall: Failed to exec postinstall script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/itsmikej/.npm/_logs/2017-09-11T06_36_35_774Z-debug.log
```

我再 package.json 里 指定了 sass 的版本 "node-sass": "^4.5.2", 但是这里貌似安装的还是3.13.1。

安装的过程中，我扫到一眼这个，不知道有没有关联：

```
npm info lifecycle yargs@7.1.0~install: yargs@7.1.0
npm info lifecycle sass-graph@2.2.4~install: sass-graph@2.2.4
npm info lifecycle node-sass@3.13.1~install: node-sass@3.13.1

> node-sass@3.13.1 install /Users/itsmikej/code/vue/vue-admin/node_modules/wysiwyg.css/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node
```

**Comment by itsmikej** [comment]
我删掉了package.json 中的 wysiwyg.css 包，现在可以正常跑起来了。。
